### ISSUE TITLE
Please update gogland

### ISSUE THREAD

**Issue by popey** [snapcrafters/gogland#1]
There's a new upstream version of gogland - 172.3757.2. Please update the yaml accordingly. Thanks.

https://download.jetbrains.com/go/gogland-172.3757.2.tar.gz

**Comment by Ads20000** [comment]
Thanks @joedborg for the update to 172.3757.46, could we have an update to 172.3968.45 and release that?

**Comment by joedborg** [comment]
Sorry @popey, I missed your request.

@Ads20000, https://github.com/snapcrafters/gogland/pull/3

**Comment by joedborg** [comment]
Released to all channels

**Comment by Ads20000** [comment]
@popey please close :)

**Comment by popey** [comment]
🎉  🍻  💃  ✔  🎶  🎧  🍺
