### ISSUE TITLE
Call for testing and release announcement in the forum

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/gogland#4]
I don't know the software well enough to do a [good call for testing thread as detailed by @popey](https://forum.snapcraft.io/t/improving-our-snap-call-for-testing-posts/1909). Please could @joedborg or someone knock up one (it may as well be called 'Call for testing: Gogland 172.3968.45 - released into stable' or something, so we can kill two checkboxes in one stone, as it were)?

Maybe I'm being a bit picky by staying we should get these checkboxes ticked but it gives people more of an opportunity to test if they so wish!

**Comment by joedborg** [comment]
@Ads20000 Will do, although I use this and PyCharm snap on a daily basis.

**Comment by popey** [comment]
Please link the call for testing in here when you do, and I'll share it out over the snapcraft social accounts. Thanks!

**Comment by joedborg** [comment]
@popey https://forum.snapcraft.io/t/call-for-testing-gogland-eap/2009

**Comment by popey** [comment]
https://twitter.com/snapcraftio/status/905390138527670273
https://www.facebook.com/snapcraftio/posts/357188098044740
https://plus.google.com/+SnapcraftIo/posts/YZgSfnr1R6e

**Comment by Ads20000** [comment]
So presumably we should do a separate release announcement when the next Gogland version comes out and we release that? :)

**Comment by Ads20000** [comment]
Hmm if we're closing this can we cheekily tick the release announcement checkbox and link to the call for testing thread?
